// Kit local de geração de ideias (funciona offline) — ângulos de argumentação no padrão Cebraspe.
// Cada ângulo traz: rot (rótulo), tpl (a ideia aplicada ao tema), como (o movimento de escrita)
// e erro (a falha típica que derruba o parágrafo).
window.DISC_IDEIAS_KIT = {
  angulos: [
    { rot: 'Causa estrutural',
      tpl: 'Causa estrutural de {T}: apontar a origem histórica/institucional do problema, não apenas o sintoma recente.',
      como: 'Recue no tempo até o desenho institucional que criou o problema e mostre por que ele persiste apesar das tentativas de correção.',
      erro: 'Trocar causa por adjetivo: dizer que a origem é "a falta de vontade política" não explica nada e não pontua.' },
    { rot: 'Causa conjuntural',
      tpl: 'Fator conjuntural que agravou {T} entre 2025 e 2026 (choque externo, decisão regulatória ou evento climático).',
      como: 'Nomeie o evento com data e explique o canal pelo qual ele piorou o quadro — evento sem mecanismo é notícia, não argumento.',
      erro: 'Confundir conjuntura com estrutura: se o problema já existia antes do evento, ele não é a causa, é o agravante.' },
    { rot: 'Consequência econômica',
      tpl: 'Consequência econômica de {T}: efeito sobre preços, crédito, emprego ou contas públicas.',
      como: 'Escolha UM canal e siga a cadeia até o fim: quem paga a conta, em que prazo e de que forma.',
      erro: 'Listar quatro efeitos em uma frase. Um efeito bem encadeado vale mais que quatro citados de passagem.' },
    { rot: 'Consequência social',
      tpl: 'Consequência social de {T}: quem é mais atingido e por quê (recorte de renda, gênero, raça, região).',
      como: 'Identifique o grupo e explique o mecanismo da desigualdade — por que ele absorve mais o impacto que os demais.',
      erro: 'Apelo emocional sem recorte. "Os mais pobres sofrem mais" só pontua se você disser por qual mecanismo.' },
    { rot: 'Marco legal',
      tpl: 'Marco normativo aplicável a {T}: lei, decreto, resolução ou dispositivo constitucional que disciplina a matéria.',
      como: 'Cite número e ano da norma e o que ela determina em concreto; se souber, indique o artigo.',
      erro: 'Citar norma errada ou inventar número. Melhor descrever o comando legal do que arriscar um número que não existe.' },
    { rot: 'Papel do Estado',
      tpl: 'Papel do Estado em {T}: competência do órgão responsável, instrumentos disponíveis e limites de atuação.',
      como: 'Nomeie o órgão certo e o instrumento que ele efetivamente detém — fiscalizar, regular, financiar ou sancionar.',
      erro: 'Atribuir ao "governo" o que é competência de agência, conselho ou ente federativo específico. Erro de competência custa caro.' },
    { rot: 'Dado / evidência',
      tpl: 'Dado datado que comprova a dimensão de {T} (citar fonte e ano).',
      como: 'Use os recortes do Repertório: fato, fonte nomeada e ano, seguidos de uma frase dizendo o que aquilo prova.',
      erro: 'Número sem fonte ou sem data. Na dúvida entre citar um dado impreciso e descrever a tendência, descreva a tendência.' },
    { rot: 'Comparação internacional',
      tpl: 'Comparação internacional: como outro país ou bloco tratou {T} e o que o Brasil pode aproveitar.',
      como: 'Compare o desenho da solução, não o resultado, e diga o que difere no contexto brasileiro que impede a cópia direta.',
      erro: 'Idealizar o estrangeiro. Comparação sem ressalva de contexto soa ingênua e é facilmente refutável.' },
    { rot: 'Contra-argumento',
      tpl: 'Objeção legítima a enfrentar em {T} — reconhecer o custo ou o risco da tese e refutá-lo.',
      como: 'Formule a objeção na versão mais forte possível e só então responda. É o parágrafo que mais separa nota alta de nota média.',
      erro: 'Construir espantalho: enfraquecer a objeção para derrubá-la fácil. O corretor percebe e desconta.' },
    { rot: 'Trade-off',
      tpl: 'Tensão entre dois valores em {T} (eficiência x equidade, liberdade x proteção, desenvolvimento x sustentabilidade).',
      como: 'Nomeie os dois valores, diga quem ganha e quem perde em cada escolha e proponha o critério que decide a disputa.',
      erro: 'Terminar em "é preciso equilíbrio". Sem o critério que define o equilíbrio, a frase não diz nada.' },
    { rot: 'Solução (agente-ação-meio-fim)',
      tpl: 'Proposta de intervenção sobre {T}: agente competente + ação concreta + meio de execução + finalidade mensurável.',
      como: 'Escreva a proposta em uma frase com os quatro elementos encadeados e verifique se dá para checar o resultado.',
      erro: 'Propor "conscientizar a população". Sem agente, meio e finalidade verificável, a proposta não pontua.' },
    { rot: 'Efeito de não agir',
      tpl: 'Cenário de inércia: o que se agrava se nada for feito quanto a {T}.',
      como: 'Projete a tendência atual e diga em que prazo o custo se torna maior que o da intervenção.',
      erro: 'Catastrofismo sem base. Projeção precisa partir de uma série ou de um dado, não do medo.' },
  ],
};
