// Dossiês de tema (Prof. Rodolfo Gracioli) — propostas P3 prontas com aspectos, para treino de dissertação.
window.DISC_DOSSIES = [
  { id: 'tiktok', area: 'Tecnologia & Inovação',
    tema: 'A "TikTokização" da sociedade: democratização da informação ou superficialização do conhecimento?',
    aspectos: [
      'Aspectos sociais: inclusão digital e voz a grupos marginalizados vs. desinformação, fake news e reforço de desigualdades no aprendizado.',
      'Aspectos culturais: cultura do viral (curtidas acima de profundidade), perda de espaço de obras longas e homogeneização cultural.',
      'Aspectos comportamentais: fragmentação da atenção e condicionamento a estímulos imediatos.',
    ] },
  { id: 'influ_mirins', area: 'Educação',
    tema: 'Influenciadores mirins e a desvalorização da escola e do trabalho formal: desafios para a formação das novas gerações',
    aspectos: [
      'Impacto na valorização da educação formal e no projeto de vida dos jovens.',
      'Exposição precoce, trabalho infantil digital e proteção da criança (ECA).',
      'Papel da família, da escola e da regulação das plataformas.',
    ] },
  { id: 'chupetas_adultos', area: 'Saúde',
    tema: 'O uso de chupetas por adultos: modismo, regressão comportamental ou busca por bem-estar?',
    aspectos: [
      'Dimensão psicológica: ansiedade, autorregulação emocional e conforto.',
      'Influência das redes sociais na normalização de comportamentos.',
      'Limites entre bem-estar individual e saúde pública.',
    ] },
  { id: 'precos_eventos', area: 'Economia',
    tema: 'A elevação de preços motivada por grandes eventos: oportunismo ou necessidade?',
    aspectos: [
      'Lógica de mercado: oferta, demanda e formação de preços.',
      'Proteção do consumidor e papel dos órgãos de defesa (CDC/Procon).',
      'Ética empresarial e limites entre lucro legítimo e abuso.',
    ] },
  { id: 'limites_humor', area: 'Sociedade',
    tema: 'Os limites do humor na sociedade contemporânea: entre a liberdade de expressão e o respeito aos direitos fundamentais',
    aspectos: [
      'Liberdade de expressão como direito fundamental e seus limites constitucionais.',
      'Discurso de ódio, discriminação e dignidade da pessoa humana.',
      'Papel das redes sociais na amplificação e na responsabilização.',
    ] },
  { id: 'senciencia_animal', area: 'Sociedade',
    tema: 'O reconhecimento da senciência animal deve transformar o tratamento jurídico dos animais no Brasil?',
    aspectos: [
      'Evolução do estatuto jurídico dos animais (de "coisa" a ser senciente).',
      'Legislação e jurisprudência recentes (guarda de pets, proteção).',
      'Implicações éticas, econômicas e de bem-estar animal.',
    ] },
  { id: 'brain_rot', area: 'Saúde',
    tema: 'Brain rot: como o uso excessivo de telas prejudica o cérebro',
    aspectos: [
      'Efeitos neurológicos e cognitivos do consumo excessivo de conteúdo digital.',
      'Impacto na atenção, memória e saúde mental, sobretudo em jovens.',
      'Estratégias de higiene digital e políticas públicas de conscientização.',
    ] },
  { id: 'wellbeing_washing', area: 'Saúde',
    tema: 'Wellbeing washing: como garantir saúde mental na esfera laboral',
    aspectos: [
      'Diferença entre ações efetivas e discurso vazio de bem-estar corporativo.',
      'Saúde mental no trabalho: dados de afastamentos e custos (NR-1, riscos psicossociais).',
      'Responsabilidade das empresas e do poder público na prevenção.',
    ] },
  { id: 'ecoansiedade', area: 'Meio Ambiente & Sustentabilidade',
    tema: 'Ecoansiedade: quando os problemas ambientais afetam a saúde',
    aspectos: [
      'Relação entre crise climática e saúde mental (angústia, medo do futuro).',
      'Grupos mais vulneráveis (jovens, populações atingidas por desastres).',
      'Enfrentamento: educação ambiental, ação coletiva e apoio psicológico.',
    ] },
  { id: 'voto_cidadania', area: 'Sociedade',
    tema: 'A democracia em questão no Brasil e o voto como exercício da cidadania',
    aspectos: [
      'Importância do voto como mecanismo de exercício da cidadania.',
      'Consequências de uma provável ruptura democrática.',
      'Ações de fortalecimento da democracia, como a educação política.',
    ] },
  { id: 'celular_escola', area: 'Educação',
    tema: 'O uso do celular deve ser banido do contexto educacional? Quais fatores as escolas podem considerar',
    aspectos: [
      'Impactos do celular na atenção, no aprendizado e na convivência escolar.',
      'BNCC e o uso pedagógico da tecnologia vs. restrição em sala.',
      'Regulação (Lei 15.100/2025), autonomia escolar e papel da família.',
    ] },
  { id: 'doacao_orgaos', area: 'Saúde',
    tema: 'A doação de órgãos deve ser automática (consentimento presumido)?',
    aspectos: [
      'Modelos de consentimento (presumido vs. expresso) e a legislação brasileira.',
      'Filas de transplante, autonomia individual e papel da família.',
      'Campanhas de conscientização e confiança no sistema de saúde.',
    ] },
  { id: 'etarismo', area: 'Sociedade',
    tema: 'Etarismo: o preconceito etário e o envelhecimento populacional no Brasil',
    aspectos: [
      'Envelhecimento populacional e seus impactos sociais e econômicos.',
      'Discriminação etária no mercado de trabalho e na saúde.',
      'Políticas públicas de proteção e valorização da pessoa idosa (Estatuto do Idoso).',
    ] },
  { id: 'racismo_ambiental', area: 'Meio Ambiente & Sustentabilidade',
    tema: 'Impactos da crise climática para a sociedade e a questão do racismo ambiental',
    aspectos: [
      'Distribuição desigual dos efeitos climáticos entre grupos raciais e sociais.',
      'Saneamento, moradia em áreas de risco e vulnerabilidade das populações negras e periféricas.',
      'Justiça climática e políticas públicas de adaptação equitativa.',
    ] },
  { id: 'cultura_indigena', area: 'Sociedade',
    tema: 'Como garantir a valorização da cultura indígena no Brasil',
    aspectos: [
      'Reconhecimento e proteção dos direitos e territórios indígenas (Marco Temporal).',
      'Educação, memória e combate ao apagamento cultural.',
      'Representatividade, protagonismo indígena e políticas públicas.',
    ] },
  { id: 'seguranca_publica', area: 'Sociedade',
    tema: 'Segurança pública no Brasil: desafios e caminhos (Anuário de Segurança Pública)',
    aspectos: [
      'Panorama da violência (homicídios, feminicídios, letalidade policial) segundo o Anuário.',
      'Combate ao crime organizado e à descapitalização de facções.',
      'Prevenção, integração de forças e políticas públicas baseadas em dados.',
    ] },
  { id: 'arte_virtualizacao', area: 'Cultura',
    tema: 'O papel das expressões artísticas em tempos de virtualização da arte',
    aspectos: [
      'Democratização do acesso à arte pelo meio digital.',
      'Impactos da virtualização na fruição, na autoria e no valor da obra.',
      'Preservação cultural e novos formatos de criação artística.',
    ] },
  { id: 'desafios_justica', area: 'Sociedade',
    tema: 'Os desafios da Justiça na contemporaneidade',
    aspectos: [
      'Acesso à Justiça, morosidade e efetivação dos direitos sociais.',
      'Papel ativo do Judiciário e judicialização das relações sociais.',
      'Tecnologia, transparência e confiança nas instituições.',
    ] },
  { id: 'crise_democracia', area: 'Sociedade',
    tema: 'A crise da democracia em tempos de violência e polarização política',
    aspectos: [
      'Polarização, desinformação e enfraquecimento do debate público.',
      'Violência política e a Lei nº 14.192/2021.',
      'Fortalecimento das instituições e da cultura democrática.',
    ] },
  { id: 'utopia_distopia', area: 'Sociedade',
    tema: 'Vivemos a era da utopia, da distopia ou da retrotopia?',
    aspectos: [
      'Persistência de mazelas sociais básicas em pleno século XXI.',
      'Tecnologia, futuro e os riscos de retrocessos (retrotopia).',
      'Caminhos para um projeto de sociedade mais justo e inclusivo.',
    ] },
  { id: 'config_familiares', area: 'Sociedade', tipo: 'P3',
    tema: 'As novas configurações familiares no Brasil',
    aspectos: [
      'Diversidade dos arranjos familiares e reconhecimento jurídico.',
      'Casamento infantil, desigualdade e proteção de vulneráveis.',
      'Direitos, políticas públicas e transformações sociais.',
    ] },

  { id: 'p4_choque_inflacao', area: 'Economia', tipo: 'P4',
    tema: 'Choque inflacionário: resposta de política monetária',
    situacao: 'Considere que a economia brasileira sofra um choque de oferta que eleve a inflação acima do teto da meta, com desancoragem das expectativas.',
    aspectos: [
      'Explique os instrumentos de política monetária que o Banco Central pode acionar e seus efeitos.',
      'Analise o papel da comunicação e da credibilidade (âncora de expectativas) no controle inflacionário.',
      'Discuta os trade-offs entre controle da inflação e atividade econômica/emprego.',
    ] },
  { id: 'p4_corrida_bancaria', area: 'Economia', tipo: 'P4',
    tema: 'Corrida bancária em instituição sistêmica',
    situacao: 'Uma instituição financeira de importância sistêmica enfrenta forte saque de depósitos e risco de contágio ao sistema.',
    aspectos: [
      'Explique o papel do Banco Central como emprestador de última instância e seus limites.',
      'Analise os instrumentos prudenciais e o mecanismo de garantia de depósitos (FGC).',
      'Discuta medidas para conter o risco de contágio e preservar a estabilidade financeira.',
    ] },
  { id: 'p4_regulacao_fintech', area: 'Tecnologia & Inovação', tipo: 'P4',
    tema: 'Prevenção à lavagem de dinheiro via fintechs',
    situacao: 'Uma fintech de pagamentos apresenta falhas de compliance que possibilitam movimentações suspeitas de lavagem de dinheiro.',
    aspectos: [
      'Explique as obrigações de PLD/FT aplicáveis e o papel do Banco Central e do COAF na supervisão.',
      'Analise os controles internos (KYC, monitoramento) que a instituição deveria adotar.',
      'Discuta o equilíbrio entre inovação/inclusão financeira e integridade do SFN.',
    ] },
  { id: 'p4_risco_climatico', area: 'Meio Ambiente & Sustentabilidade', tipo: 'P4',
    tema: 'Risco climático no balanço de um banco',
    situacao: 'Um banco possui carteira de crédito exposta a setores vulneráveis a eventos climáticos e à transição para baixo carbono.',
    aspectos: [
      'Explique os canais pelos quais o risco climático (físico e de transição) afeta a solidez do banco.',
      'Analise como incorporar o risco climático na gestão prudencial e nos testes de estresse.',
      'Discuta o papel do regulador na exigência de divulgação e mitigação desses riscos.',
    ] },
];
