// Banco de temas de atualidades por área — candidatos a proposta discursiva Cebraspe/BACEN.
// Ordem dentro de cada área: MAIS RECENTE / MAIS PROVÁVEL primeiro (2026 → 2025 → estruturais).
window.DISC_TEMAS = [
  { area: 'Sistema Financeiro & Banco Central', icon: '🏛️', temas: [
    'Autonomia do Banco Central e credibilidade da política monetária',
    'Juros altos por mais tempo: custo social do combate à inflação (2026)',
    'Desancoragem das expectativas de inflação e o sistema de metas contínuas',
    'Drex e a moeda digital de banco central (CBDC) no SFN',
    'Pix, Pix Automático e Pix parcelado: inclusão financeira e riscos',
    'Open Finance e o compartilhamento de dados bancários',
    'Regulação de bets e o endividamento das famílias',
    'Criptoativos: Lei 14.478/2022 e a regulação do BC',
    'Risco climático e estresse dos bancos (Resoluções CMN de sustentabilidade)',
    'Cibersegurança no SFN: fraudes, vazamentos e ataques a instituições',
    'Educação financeira como política pública',
    'Basileia III, capital regulatório e estabilidade sistêmica',
    'Split payment da CBS e o papel do sistema de pagamentos',
  ] },
  { area: 'Economia', icon: '📈', temas: [
    'Reforma Tributária do consumo: 2026 como ano de teste do IBS e da CBS',
    'Tarifaço dos EUA e a reorientação do comércio exterior brasileiro',
    'Inflação acima do teto da meta e o dilema do Copom em 2026',
    'Dívida pública, arcabouço fiscal e sustentabilidade das contas',
    'Choque do petróleo e repasse aos preços domésticos',
    'Dependência de commodities e reprimarização da pauta exportadora',
    'Acordo Mercosul-União Europeia: oportunidades e resistências',
    'Desindustrialização e política industrial (Nova Indústria Brasil)',
    'Concentração bancária e custo do crédito',
    'Informalidade no mercado de trabalho e produtividade',
    'Desigualdade de renda e tributação sobre altas rendas',
    'Envelhecimento populacional e sustentabilidade previdenciária',
    'Transição energética como vantagem competitiva brasileira',
  ] },
  { area: 'Administração Pública & Governança', icon: '⚖️', temas: [
    'Governo digital e simplificação do atendimento ao cidadão',
    'Uso de IA na administração pública: eficiência e responsabilização',
    'Lei de Acesso à Informação e transparência ativa',
    'Improbidade administrativa após a Lei 14.230/2021',
    'Integridade, compliance público e prevenção à corrupção',
    'Concursos públicos e o Concurso Nacional Unificado',
    'Avaliação de políticas públicas e orçamento por resultados',
    'Emendas parlamentares e transparência na execução orçamentária',
    'Ética no serviço público e conflito de interesses',
    'Consensualidade e resolução de conflitos na Administração',
  ] },
  { area: 'Tecnologia & Inovação', icon: '💡', temas: [
    'Regulação da inteligência artificial: modelo brasileiro e AI Act europeu',
    'Deepfakes e integridade do processo eleitoral (Resolução TSE 23.748/2026)',
    'IA generativa e o futuro do trabalho qualificado',
    'ECA Digital: dever de cuidado das plataformas e verificação de idade',
    'Consumo de energia e água por data centers de IA',
    'Soberania digital e dependência de infraestrutura estrangeira',
    'Governança global da IA e a posição do Sul Global (BRICS)',
    'LGPD, ANPD e a proteção de dados como direito fundamental',
    'Desinformação, moderação de conteúdo e liberdade de expressão',
    'Inclusão digital e o custo da conectividade no Brasil',
    'Automação, plataformização e direitos dos trabalhadores de aplicativo',
  ] },
  { area: 'Meio Ambiente & Sustentabilidade', icon: '🌱', temas: [
    'Legado da COP30 em Belém e as metas climáticas brasileiras (NDC)',
    'Financiamento climático e o papel dos bancos centrais',
    'Mercado regulado de carbono no Brasil (Lei 15.042/2024)',
    'Eventos climáticos extremos e adaptação das cidades',
    'Desmatamento na Amazônia: queda recente e desafios de consolidação',
    'Exploração de petróleo na Foz do Amazonas: dilema desenvolvimento x clima',
    'Transição energética justa e matriz elétrica renovável',
    'Segurança hídrica e crise dos aquíferos',
    'ESG: risco de greenwashing e padronização de métricas',
    'Bioeconomia e valor agregado da floresta em pé',
    'Agenda 2030 e o atraso global nos ODS',
  ] },
  { area: 'Sociedade', icon: '👥', temas: [
    'Adultização e proteção de crianças e adolescentes nas redes',
    'Violência de gênero e feminicídio: da lei à efetividade',
    'Racismo estrutural e políticas afirmativas após a revisão das cotas',
    'Saúde mental da juventude e uso intensivo de telas',
    'Envelhecimento populacional, etarismo e cuidado',
    'Trabalho de cuidado não remunerado e desigualdade de gênero',
    'Fome, insegurança alimentar e programas de transferência de renda',
    'Moradia, déficit habitacional e gentrificação',
    'Povos originários e o Marco Temporal das terras indígenas',
    'Polarização política e erosão da confiança nas instituições',
  ] },
  { area: 'Segurança', icon: '🛡️', temas: [
    'Facções criminosas e a economia do crime organizado',
    'Lavagem de dinheiro, PLD/FT e o papel do Coaf',
    'Reconhecimento facial e vieses algorítmicos no policiamento',
    'Golpes digitais, fraudes no Pix e proteção do consumidor bancário',
    'Segurança cibernética de infraestruturas críticas',
    'Sistema prisional, superlotação e reincidência',
    'Política de drogas e descriminalização',
    'Violência armada e controle de armas',
  ] },
  { area: 'Saúde', icon: '🏥', temas: [
    'Financiamento do SUS e subfinanciamento crônico',
    'Saúde mental no trabalho: afastamentos recordes e NR-1',
    'Arboviroses, dengue e vacinação em dose única',
    'Hesitação vacinal e recomposição da cobertura',
    'Canetas emagrecedoras: acesso, uso off-label e regulação',
    'Telessaúde e IA no diagnóstico médico',
    'Judicialização da saúde e incorporação de tecnologias',
    'Determinantes sociais da saúde e equidade no acesso',
    'Preparação para novas pandemias e vigilância genômica',
  ] },
  { area: 'Educação', icon: '📚', temas: [
    'Novo PNE (2026-2036): metas e financiamento',
    'IA na sala de aula: diretrizes do MEC e da Unesco',
    'Restrição ao celular nas escolas e aprendizagem',
    'Alfabetização na idade certa e o Compromisso Nacional',
    'Evasão no ensino médio e trabalho precoce',
    'Qualidade da educação superior privada e regulação do MEC',
    'Educação financeira e empreendedora na BNCC',
    'Formação e valorização docente',
  ] },
  { area: 'Relações Internacionais', icon: '🌍', temas: [
    'Guerra no Oriente Médio e o preço do petróleo',
    'Estreito de Ormuz: gargalo logístico e risco global',
    'Rússia-Ucrânia no quinto ano: efeitos sobre alimentos e energia',
    'Fragmentação da ordem multilateral e reforma da ONU',
    'BRICS ampliado e desdolarização parcial do comércio',
    'Protecionismo, guerra tarifária e cadeias globais de valor',
    'Crise migratória e responsabilidade compartilhada',
    'Brasil como potência ambiental e diplomacia climática',
  ] },
  { area: 'Trabalho & Renda', icon: '🧰', temas: [
    'Regulamentação do trabalho por aplicativos',
    'Jornada 6x1 e redução da jornada de trabalho',
    'Igualdade salarial entre homens e mulheres (Lei 14.611/2023)',
    'Requalificação profissional diante da automação',
    'Trabalho análogo à escravidão e fiscalização',
    'Home office, direito à desconexão e produtividade',
  ] },
  { area: 'Transportes & Cidades', icon: '🚦', temas: [
    'Tarifa zero e financiamento do transporte público',
    'Eletrificação da frota e infraestrutura de recarga',
    'Mobilidade ativa: ciclovias e segurança viária',
    'Concessões e parcerias público-privadas em infraestrutura',
  ] },
  { area: 'Cultura', icon: '🎬', temas: [
    'Direitos autorais e obras geradas por IA',
    'Política Nacional Aldir Blanc e fomento descentralizado',
    'Audiovisual brasileiro, streaming e cota de conteúdo nacional',
    'Patrimônio cultural e preservação de acervos',
  ] },
];
